//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub header_markdown: String,
    #[sea_orm(column_type = "Text")]
    pub header_html: String,
    #[sea_orm(column_type = "Text")]
    pub footer_markdown: String,
    #[sea_orm(column_type = "Text")]
    pub footer_html: String,
    #[sea_orm(column_type = "Text")]
    pub css: String,
    #[sea_orm(column_type = "Text")]
    pub javascript: String,
    pub posts_per_page: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
